import { PanelWithReading } from './types'

export const DUMMY_PANELS: PanelWithReading[] = [
  {
    id: 'dummy-panel-01',
    tenant_id: 'tenant-demo',
    name: 'Panel MDB Gedung Utama',
    location_label: 'Lantai 1 - Ruang Trafo & Panel Utama',
    floor_x: 28,
    floor_y: 35,
    is_active: true,
    created_at: new Date().toISOString(),
    latest_reading: {
      id: 'read-01',
      panel_id: 'dummy-panel-01',
      tenant_id: 'tenant-demo',
      voltage: 221.4,
      current_a: 18.2,
      power: 4030,
      temperature_panel: 38.5,
      temperature_ambient: 29.1,
      frequency: 50.02,
      power_factor: 0.96,
      arc_detected: false,
      status: 'normal',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'dummy-panel-02',
    tenant_id: 'tenant-demo',
    name: 'Panel Distribusi Lab Komputer',
    location_label: 'Gedung B - Lantai 2 Lab IT & Robotika',
    floor_x: 62,
    floor_y: 28,
    is_active: true,
    created_at: new Date().toISOString(),
    latest_reading: {
      id: 'read-02',
      panel_id: 'dummy-panel-02',
      tenant_id: 'tenant-demo',
      voltage: 216.8,
      current_a: 36.4,
      power: 7890,
      temperature_panel: 58.6,
      temperature_ambient: 32.4,
      frequency: 49.94,
      power_factor: 0.91,
      arc_detected: false,
      status: 'warning',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'dummy-panel-03',
    tenant_id: 'tenant-demo',
    name: 'Panel Daya Aula & Multimedia',
    location_label: 'Gedung C - Ruang Sound & Lighting Panggung',
    floor_x: 75,
    floor_y: 68,
    is_active: true,
    created_at: new Date().toISOString(),
    latest_reading: {
      id: 'read-03',
      panel_id: 'dummy-panel-03',
      tenant_id: 'tenant-demo',
      voltage: 204.2,
      current_a: 54.8,
      power: 11190,
      temperature_panel: 79.4,
      temperature_ambient: 35.8,
      frequency: 49.68,
      power_factor: 0.84,
      arc_detected: true,
      status: 'danger',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'dummy-panel-04',
    tenant_id: 'tenant-demo',
    name: 'Panel Pompa Air & Sarpras',
    location_label: 'Area Luar - Ruang Mesin Sanitasi',
    floor_x: 35,
    floor_y: 72,
    is_active: true,
    created_at: new Date().toISOString(),
    latest_reading: {
      id: 'read-04',
      panel_id: 'dummy-panel-04',
      tenant_id: 'tenant-demo',
      voltage: 220.6,
      current_a: 14.1,
      power: 3110,
      temperature_panel: 34.2,
      temperature_ambient: 28.5,
      frequency: 50.01,
      power_factor: 0.97,
      arc_detected: false,
      status: 'normal',
      created_at: new Date().toISOString(),
    },
  },
]
